apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-agent
spec:
  selector:
    matchLabels:
      app: tarian-cluster-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: tarian-cluster-agent
    spec:
      serviceAccountName: kube-rbac-proxy
      containers:
      - name: tarian-cluster-agent
        image: localhost:5000/tarian-cluster-agent:latest
        args:
        - --log-encoding=json
        - --log-level=debug
        - run
        - "--server-address=tarian-server:80"
        ports:
        - containerPort: 50052
          name: grpc
      - name: kube-rbac-proxy
        image: localhost:5000/kube-rbac-proxy:latest
        args:
        - "--secure-listen-address=0.0.0.0:8443"
        - "--upstream=http://127.0.0.1:50052/"
        - "--upstream-force-h2c"
        - "--v=10"
        ports:
        - containerPort: 8443
          name: https
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-agent
  labels:
    app: cluster-agent
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 50052
    nodePort: 31052
    name: grpc
  - port: 443
    targetPort: 8443
    name: tls
  selector:
    app: tarian-cluster-agent
---

